global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8888'
          - 'asset-service:8080'
          - 'telemetry-service:8080'
          - 'alert-service:8080'
          - 'gateway-service:8080'
        labels:
          application: 'greenko-microservices'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'
        labels:
          service: 'container-metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'
