spring:
  application:
    name: telemetry-service

  config:
    import: optional:configserver:http://config-server:8888

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    use-root-path: true

