# Gateway Service - Minimal Local Configuration
# All other configurations are fetched from Config Server

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: default
